config/routes.rb
Rails.application.routes.draw do
  resources :timeslots
  resources :teams
  resources :coaches

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  has_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :coach
  has_and_belongs_to_many :timeslots
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_and_belongs_to_many :teams
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  has_and_belongs_to_many :teams
  
  def enough_teams?
    self.teams.length >= 4
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
    @teams = @coach.teams
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)
    password = BCrypt::Password.create(@coach.password)
    @coach.password = password
    
    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:name, :email, :password)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team_timeslots = @team.timeslots
  end

  # GET /teams/new
  def new
    @team = Team.new
    @coaches = Coach.all
    @timeslots = Timeslot.all
    @teams_timeslots = @team.timeslots
  end

  # GET /teams/1/edit
  def edit
    @coaches = Coach.all
    @timeslots = Timeslot.all
    @teams_timeslots = @team.timeslots
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)
    params[:team][:timeslots].each do |timeslot_id|
      @team.timeslots << Timeslot.find(timeslot_id)
    end
    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    
    # TODO probably a better way to use ActiveRecord to clear and add all of these
    @team.timeslots.clear
    params[:team][:timeslots].each do |timeslot_id|
      @team.timeslots << Timeslot.find(timeslot_id)
    end
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :coach_id)
    end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :set_timeslot, only: [:show, :edit, :update, :destroy]

  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
    @teams = @timeslot.teams
  end

  # GET /timeslots/new
  def new
    @timeslot = Timeslot.new
  end

  # GET /timeslots/1/edit
  def edit
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(timeslot_params)

    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully created.' }
        format.json { render :show, status: :created, location: @timeslot }
      else
        format.html { render :new }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timeslots/1
  # PATCH/PUT /timeslots/1.json
  def update
    respond_to do |format|
      if @timeslot.update(timeslot_params)
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeslot }
      else
        format.html { render :edit }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot.destroy
    respond_to do |format|
      format.html { redirect_to timeslots_url, notice: 'Timeslot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeslot
      @timeslot = Timeslot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeslot_params
      params.require(:timeslot).permit(:time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% @coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing Coach</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td><%= link_to 'Show', coach %></td>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coach', new_coach_path %>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coach.name %>
</p>

<% @teams.each do |team| %>
  <h3>
    Team Name - <%= team.name %>
  </h3>
  <ul>
    <% team.timeslots.each do |timeslot| %>
      <li>
        <%= timeslot.time %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ltab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
  <footer>
    <hr>
    <a href="<%= teams_path %>">Teams</a>
    <br>
    <a href="<%= coaches_path %>">Coaches</a>
    <br>
    <a href="<%= timeslots_path %>">Time Slots</a>
  </footer>
</body>
</html>

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timeslots/_form.html.erb
<%= form_for(@timeslot) do |f| %>
  <% if @timeslot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
      <% @timeslot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing Timeslot</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Timeslots</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td <% if timeslot.enough_teams? %> class="enough_teams" <% end %>><%= timeslot.time %></td>
        <td>
          <ul>
            <% timeslot.teams.each do |team| %>
              <li>
                <%= team.name %>
              </li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', timeslot %></td>
        <td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
        <td><%= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p class="enough_teams">
  Timeslots in red have at least 4 available teams
</p>

<br>

<%= link_to 'New Timeslot', new_timeslot_path %>

app/views/timeslots/new.html.erb
<h1>New Timeslot</h1>

<%= render 'form' %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @timeslot.time %>
</p>

<h3>
  Teams Available
</h3>
<ul>
  <% @teams.each do |team| %>
    <li>
      <%= team.name %> - Coach <%= team.coach.name %>
    </li>
  <% end %>
</ul>
<%= link_to 'Edit', edit_timeslot_path(@timeslot) %> |
<%= link_to 'Back', timeslots_path %>